### ISSUE TITLE
Contribute - what license is this published under?

### ISSUE THREAD

**Issue by agehrke** [AndyPook/A6k.Nats#1]
Hi Andy

This looks very great. I saw the issue you created in Bedrock repo. During my summer holiday I have spend a couple of nights trying to get started on exact same thing - though I decided to start without using the Bedrock framework as I thought it might change with the new connection abstractions in .NET 5.

I would like to contribute to make your NATS client production ready. My goal is to be able to use it in our 30k+ message/s messaging infrastructure at my day job.

Would you mind adding some license info to the repo? Eg [https://github.com/dotnet/aspnetcore/blob/master/LICENSE.txt](https://github.com/dotnet/aspnetcore/blob/master/LICENSE.txt) 

Andreas

**Comment by AndyPook** [comment]
Hi, nice to have someone show an interest.
There already is a LICENSE file, no? I've just used MIT.

The "plan" such as it is, is to have high throughput/performance, threadsafe, async protocol handler. The current NATS.Client package is fine but it is modelled after the go client, so it's not idiomatic c# and there are far too many locks.
The PUB path is pretty decent. Although SUB works, the semantics are not quite right yet. The details are not quite clear from the doc. But their Slack i very helpful. I don't think it's too far from good.
Then, handling disconnects and reconnects (using the INFO).
Then it'll be about adding tls, authentication etc

30k mps ought to be easy (depending on size etc)

More than happy to take PRs, suggestions 😃

**Comment by agehrke** [comment]
Dooh, yes, no idea how I missed that. 

Yes, I looked at the source code of official nats client and felt the exact same thing as you describe. 

I have a small change to WriteInt method on NatsWriter ready in a branch. But just when I was about to create PR I notified an extension method on a BufferWriter in Bedrock which does the same thing. Do you have any insights on why you are not using that BufferWriter?

**Comment by AndyPook** [comment]
This is were we need to understand that Bedrock is a set of ideas. Things have changed.
NatsWriter came from another project (A6k.Kafka which was were I started getting into Bedrock) and that came from the original Bedrock Writer.

It is entirely possible/probable that I have accidentally mutated something along the way. This was the intent of splitting the writer into partials. I was _trying_ to keep the bottom part at least similar to the original so that I could just drop in the "new" version.
But, to be open, I have been trying to just bury these bits so that I can focus on the higher level protocol/client. I have definitely dropped the ball on some of the low level bits (it "works" so move on 😬 )

When I get something that I can actually use with nats, the idea was to back track and revisit the low level: zero-copy; structs; ValueTask; channels etc

Now that PUB & SUB "work" (mostly) maybe now's the time to take another pass at this layer of stuff?

**Comment by AndyPook** [comment]
If you are interested in this. Maybe find their Slack? They have a dotnet channel. I've been able to get some good info from there.
